Implement some requests
codx-dev/dap-reactor pull request #5
Opened 2022-09-20 23:07 UTC by Daksh14

**Describe the change**
Effort to close #2. Implement 
- [X] BreakpointLocations
- [X] ConfigurationDone
- [X] Continue
- [X] Evaluate

Effort to close #3. Implement
- [X] Requests module

**Introduced tech-debts**
added more undocumented code

**Base issue**
Move efforts to #2. Effort to close #3

**Related issues**
N/A

**Additional context**
Add any other context about the change here.

2022-09-20 23:44 UTC, vlopes11 requested changes
Better not include IDE specific stuff in the repo (`.idea`)

2022-09-21 00:00 UTC, vlopes11 requested changes
A couple of nits before we are ready to merge

2022-09-21 00:00 UTC, vlopes11 commented on src/request.rs
> +            "breakpointLocations" => {
`configurationDone`, `continue` and `evaluate` seems to be missing here. Shouldn't we have a test checking for that?

2022-09-21 00:00 UTC, vlopes11 commented on src/request/evaluate.rs
> +    pub context: Option<String>,
This is an enum in the [specs](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Evaluate) and should be implemented as such here.

Example:
https://github.com/codx-dev/dap-reactor/blob/bdb1c3a671418227a5327c7ef33d145a9b41f175/src/event.rs#L10-L16

2022-09-21 00:00 UTC, vlopes11 commented on src/request/tests.rs
> +        // FIXME: The test cases with bool fields and false values don't pass the test
The encoding format is designed to be optimal in the sense of not serializing redundant fields. Probably the reason for not passing is that we don't add optional booleans as `field: false` in the json since these can, instead, don't be included.

2022-09-21 00:00 UTC, vlopes11 commented on src/response.rs
> +    BreakpointLocations,
Shouldn't this contain a vec of `BreakpointLocation`?

2022-09-21 00:00 UTC, vlopes11 commented on src/response.rs
> +    Continue,
Shouldn't this contain a body with `allThreadsContinued`?

2022-09-21 00:00 UTC, vlopes11 commented on src/response.rs
> +    Evaluate,
The response is a rather complex struct and should be added

2022-09-21 00:00 UTC, vlopes11 commented on src/types.rs
> +pub struct ValueFormat {
I can't see this type in the specs (ie specs/types/value.*). Is it part of some argument? If yes, it should be prefixed so we can easily find its counterpart in the specs

2022-09-21 01:08 UTC, Daksh14 commented on src/types.rs
> +pub struct ValueFormat {
https://microsoft.github.io/debug-adapter-protocol/specification#Types_ValueFormat You can find it here in the spec

2022-09-23 12:04 UTC, vlopes11 commented on .gitignore
> +.idea/**/sonarlint/
Maybe instead we just ignore anything inside `.idea`?

2022-09-23 12:04 UTC, vlopes11 commented on src/lib.rs
> +pub mod models;
How would models fit the protocol schema? (requests/events/respose/types)

2022-09-23 12:17 UTC, Daksh14 commented on src/lib.rs
> +pub mod models;
It doesn't. I think it's the only way to keep structures grouped correctly. A module is named by the request it is then it has impls + structured for response too.

2022-09-23 12:17 UTC, Daksh14 commented on .gitignore
> +.idea/**/sonarlint/
Sure! Let's do that

2022-09-26 17:30 UTC, vlopes11 requested changes
couple of nits

2022-09-26 17:30 UTC, vlopes11 commented on src/models/breakpoint_locations.rs
> +    pub end_column: Option<u64>,
This is redundant to `BreakpointLocationsArguments` and is skipping `source`. According to the specs, we have a single optional field `arguments` that containts `Option<BreakpointLocationsArguments>`

2022-09-26 17:30 UTC, vlopes11 commented on src/models/configuration_done.rs
> +}
Should be `From<&Map<String, Value>>` since its infallible

2022-09-26 17:30 UTC, vlopes11 commented on src/models/continue.rs
> +impl TryFrom<&Map<String, Value>> for ContinueArguments {
line break missing

2022-09-26 17:30 UTC, vlopes11 commented on src/models/continue.rs
> +        let all_threads_continued = utils::get_bool_optional(map, "allThreadsContinued")?;
According to the specs, this is a child of `body`

2022-09-26 17:30 UTC, vlopes11 commented on src/models/continue.rs
> +            utils::attribute_bool("allThreadsContinued", all_threads_continued);
Ditto; its `body` in the specs

2022-09-26 17:30 UTC, vlopes11 commented on src/models/evaluate.rs
> +    pub context: Option<Context>,
Should prefix the enum with the evaluate arguments domain so it won't mix with root `Context` objects. Example: `EvaluateArgumentsContext`

2022-09-26 17:30 UTC, vlopes11 commented on src/models/evaluate.rs
> +    pub named_variables: Option<String>,
Its `number` in the specs

2022-09-26 18:43 UTC, Daksh14 commented on src/models/evaluate.rs
> +    pub context: Option<Context>,
Since it's in a module, we won't have to prefix it, that's one thing I love about rust modules. If there are two contexts in the scope, rust will error out and if you want the context to be from evaluate then you have all the control. We leave this job to the user of the library.

```rust
use crate::models::evaluate::Context; // get context from evaluate.rs

use crate::models::evaluate::Context as EvaluateContext; // or EvaluateArgumentsContext 
```
or
```rust
use crate::models::*;

let context_evaluate = evaluate::Context::default();
```

2022-09-26 18:47 UTC, Daksh14 commented on src/models/evaluate.rs
> +    pub named_variables: Option<String>,
Fixed in [f77b934](https://github.com/codx-dev/dap-reactor/pull/5/commits/f77b934abf6908394f6be4018c2ebf40fe0ece68)

2022-09-26 18:47 UTC, Daksh14 commented on src/models/continue.rs
> +impl TryFrom<&Map<String, Value>> for ContinueArguments {
Fixed in [f77b934](https://github.com/codx-dev/dap-reactor/pull/5/commits/f77b934abf6908394f6be4018c2ebf40fe0ece68)

2022-09-26 18:47 UTC, Daksh14 commented on src/models/configuration_done.rs
> +}
Fixed in [f77b934](https://github.com/codx-dev/dap-reactor/pull/5/commits/f77b934abf6908394f6be4018c2ebf40fe0ece68)

2022-09-26 18:47 UTC, Daksh14 commented on src/models/breakpoint_locations.rs
> +    pub end_column: Option<u64>,
Good catch, changed to optional. 

Fixed in [f77b934](https://github.com/codx-dev/dap-reactor/pull/5/commits/f77b934abf6908394f6be4018c2ebf40fe0ece68)

2022-09-26 20:11 UTC, vlopes11 commented on src/models/evaluate.rs
> +    pub context: Option<Context>,
Prefixing by module isn't friendly for `prelude` imports, as in https://github.com/codx-dev/dap-reactor/blob/019f22984c86e86d3723c4a235a98ab65dd2aee8/examples/async.rs#L3

2022-09-26 20:16 UTC, Daksh14 commented on src/models/evaluate.rs
> +    pub context: Option<Context>,
Yes. If there are two 'Context', that means it's an ambigious import so rust will error out and tell you to import the Context you want to use. This also allows the user to prefix the structs in the way they want in their codebase. Us prefixing it will not be ideal then. This means its more idomatic.

2022-09-26 22:12 UTC, vlopes11 commented on src/models/evaluate.rs
> +    pub context: Option<Context>,
The main concern lies around rules and generalizations. The rule we have now for other types that can be generalized is to prefix the concrete ones with their specific usages, if applicable.

We have that rule, for example, here:
https://github.com/codx-dev/dap-reactor/blob/f77b934abf6908394f6be4018c2ebf40fe0ece68/src/types.rs#L114

It means that we will need to either refactor all these other types - and maybe fall into a scenario where we might have a naming conflict - or prefix this one to comply with the others. What is undesirable is to have different naming conventions for the same class of concrete types in the same library

2022-09-26 22:17 UTC, Daksh14 commented on src/models/evaluate.rs
> +    pub context: Option<Context>,
That is true and sticking to module prefixing achieves the same. We can name modules exactly like the specification.

2022-09-26 22:19 UTC, vlopes11 commented on src/models/evaluate.rs
> +    pub context: Option<Context>,
Should we include this change to the other types in this PR then?

2022-09-26 22:25 UTC, Daksh14 commented on src/models/evaluate.rs
> +    pub context: Option<Context>,
I suggest so. Create an issue so we don't forget it!

2022-09-27 01:53 UTC, Daksh14 commented on src/models/evaluate.rs
> +    pub context: Option<Context>,
#3 will fix this issue.

2022-09-27 09:55 UTC, vlopes11 approved these changes

2022-09-28 05:23 UTC, merged